apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: my1-node-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: my1
 template:
   metadata:
     labels:
       app: my1
   spec:
     containers:
     - name: my1
       image: karthi696/my1:latest
       ports:
       - containerPort: 5000
